### PR TITLE
Remove timeouts

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by Slayer95** [comment]
@spalger, apparently the build for the current version of the package is failing (which is odd since the badge in the readme displays "passing"). Maybe some dependency update broke it?

**Comment by spalger** [comment]
@Slayer95 the "current" build is just the latest build of the pr
 - https://travis-ci.org/spalger/gulp-jshint/builds
 - https://travis-ci.org/spalger/gulp-jshint/pull_requests

**Comment by spalger** [comment]
The badge on the repo is filtered to the master branch

> https://travis-ci.org/spalger/gulp-jshint.svg?branch=master

**Comment by Slayer95** [comment]
Actually, the `Current tab` displays a different commit with a minimal delta that I pushed to this branch before
https://github.com/spalger/gulp-jshint/commit/5e989cccc6d7e43ffe99465e292f022cd991b56d

And it also fails the build.
https://travis-ci.org/spalger/gulp-jshint/jobs/65357850

Running `gulp test` locally also fails before this commit.

Probably the `passing` result is simply a cache from a previous sucessful build?

**Comment by spalger** [comment]
hmm, tests run fine for me. What failure do you get?
image

**Comment by Slayer95** [comment]
`npm version`, `npm ls`, and `gulp test`:

http://hastebin.com/orilofegih.tex

This patch fixes the failing tests for me, but it may or may not be the ideal fix

http://hastebin.com/elaruboqur.js

**Comment by Slayer95** [comment]
Both failing tests pass on reversion to JSHint 2.7.0.
Apparently, from 2.7.0 to 2.8.0 the errors and warnings change:

jshint@2.8.0
E2 W0 I0
E4 W0 I0

jshint@2.7.0
E2 W2 I0
E4 W4 I0

It looks like https://github.com/spalger/gulp-jshint/commit/ad8ce6043aee3d045c1c059d079ffcb24d8b203e passed the tests due to pure chance.
https://github.com/spalger/gulp-jshint/pull/114 fixes this.

**Comment by Slayer95** [comment]
Rebased and it passes now! :]

**Comment by spalger** [comment]
Thanks @Slayer95 :)

**Pull request merged**
