### PR TITLE
Use relative file path in reporter

### LINKED ISSUE #101: Use relative paths in error results
The JSHint "spec" (http://jshint.com/docs/reporters/) describe the "file" key as a relative path (file: 'demo.js') and grunt-jshint also uses that format. Changing file.path to file.relative in lint.js/reportErrors would allow the reporters to output paths relative to the project's root, removing some clutter from the jshint output.

However a test (integration/fileIgnored.js) is making sure that the base property is not accessed, which is the case with the file.relative assessor. Is there any reason to use an absolute path? Would an extra option could be added for that?

### PR DESCRIPTION
**Pull request by IcanDivideBy0**
fixes #101

### CODE REVIEW

**Comment by unreadableusername** [comment]
:+1:

**Comment by unreadableusername** [comment]
@IcanDivideBy0 maybe it's better to add an option 'relative' and depends on it to show full or relative path

**Comment by IcanDivideBy0** [comment]
@unreadableusername as pointed in the issue :
> The JSHint "spec" (http://jshint.com/docs/reporters/) describe the "file" key as a relative path

So if there should be an option for that, it should be an `--absolute` option. Is that really worth ?

**Comment by spalger** [comment]
LGTM. Thanks @IcanDivideBy0

**Comment by xtianjohns** [comment]
Hey @spalger, do you know when you might publish to npm? I know there are a handful of PRs that have been merged, this just happens to be one I'm really interested in. If you plan to wait for a bit while more requests get reviewed, I might just temporarily update my package.json to download 5b73861925d35fdfe86db6dccfe9e7c929209464.

**Comment by spalger** [comment]
@xtianjohns sorry it took so long, just released as 1.12.0

**Comment by xtianjohns** [comment]
No big at all - perfect timing! Thanks!

**Pull request merged**
