### PR TITLE
Update rcloader version

### LINKED ISSUE #142: deprecated dependencies
`npm` warns about lodash@<3.0.0, which is depended on by rcloader@0.1.2, which is depended on by this package. The current version of rcloader has current lodash dependencies that will get rid of this message.

### PR DESCRIPTION
**Pull request by zbjornson**
Fix #142

### CODE REVIEW

**Comment by spalger** [comment]
iirc there is a reason why I didn't upgrade to 0.2, but I can't remember right now...

**Comment by zbjornson** [comment]
Hrm. :confused: I've used my fork for the last few days in a repo with deeply nested rc files. Can keep using it locally for another week or so and let you know if I hit problems if you want.

**Comment by spalger** [comment]
Thanks, that'd be great

**Comment by zbjornson** [comment]
So far: working on 3 different computers (Win10 and Ubuntu) in a repo with ~5 nested RC files

**Pull request closed without merging**
