### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by chasemgray**
Fix auto updating to 2.9.0-RC1

### CODE REVIEW

**Comment by Dillonmcewan** [comment]
+1

**Comment by seaster** [comment]
+1

**Comment by mprentic-harris** [comment]
This would be nice. We've seen some really odd behaviors and inconsistencies due to this with different machines pulling in 2.8.0 and other versions of JSHint with different behaviors.

**Comment by stanjer** [comment]
Is it possible to be merged and included to release? It's blocking using latest lodash version, as usage changed significantly

**Comment by spalger** [comment]
Closing this as jshint is now a peer dependency and you can pin it to whatever version you like by installing gulp-jshint 2

```sh
npm install --save-dev jshint@2.8 gulp-jshint@latest
```

**Comment by mprentic-harris** [comment]
@spalger thank you!

**Pull request closed without merging**
